### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by Radu1990**
Hi Arun, can we merge these changes to master branch ?

### CODE REVIEW

**Comment by Arun-KumarH** [comment]
Hi Radu,
The tests seem to be failing in travis, pls check that.
Also rebase the branch to master (I see conflict - package.json).

**Comment by Radu1990** [comment]
ok now the pass

**Comment by Arun-KumarH** [comment]
https://github.com/restorecommerce/ostorage-srv/blob/test-branch/src/service.ts#L173 - this should not be treated as error.

**Comment by vanthome** [comment]
@Arun-KumarH why not? that is an unexpected case as far as I understood.

**Comment by Arun-KumarH** [comment]
@vanthome this was exactly the issue with old minio version, some systems might not throw an error if rules are not configured and data would be empty as well - so we should log it as no rules configured for this case and resolve it.

**Comment by vanthome** [comment]
Let's just consider the behaviour as it is with the current version of Minio, so for previous versions I'm find if that makes the service fail. Users can see in the log that something went wrong (which was not the case before I think).

**Pull request closed without merging**
